<?php
/**
 * JPWRT - Blog program based on jsnpp
 * Author: A.J <804644245@qq.com>
 * Copyright: JPWRT [http://www.jpwrt.com] All rights reserved.
 * Licensed: Apache-2.0
 * GitHub: https://github.com/yanzicms/jpwrt
 */
return [
    'users' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'username', 'type' => 'VARCHAR', 'length' => 50, 'default' => '', 'index' => 'username'],
        ['name' => 'password', 'type' => 'VARCHAR', 'length' => 64, 'default' => ''],
        ['name' => 'nickname', 'type' => 'VARCHAR', 'length' => 50, 'default' => ''],
        ['name' => 'firstname', 'type' => 'VARCHAR', 'length' => 50, 'default' => ''],
        ['name' => 'lastname', 'type' => 'VARCHAR', 'length' => 50, 'default' => ''],
        ['name' => 'publicname', 'type' => 'VARCHAR', 'length' => 50, 'default' => ''],
        ['name' => 'email', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'email'],
        ['name' => 'url', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'avatar', 'type' => 'VARCHAR', 'length' => 255, 'default' => ''],
        ['name' => 'gender', 'type' => 'SMALLINT', 'default' => 0],
        ['name' => 'birthday', 'type' => 'DATE'],
        ['name' => 'signature', 'type' => 'TEXT'],
        ['name' => 'createtime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'lastime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'lastip', 'type' => 'VARCHAR', 'length' => 255, 'default' => ''],
        ['name' => 'activation', 'type' => 'VARCHAR', 'length' => 60, 'default' => ''],
        ['name' => 'randomcode', 'type' => 'VARCHAR', 'length' => 60, 'default' => ''],
        ['name' => 'status', 'type' => 'INT', 'default' => 1],
        ['name' => 'usertype', 'type' => 'VARCHAR', 'length' => 50, 'default' => ''],
        ['name' => 'language', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'integral', 'type' => 'INT', 'default' => 0, 'index' => 'integral'],
        ['name' => 'posts', 'type' => 'INT', 'default' => 0],
        ['name' => 'comments', 'type' => 'INT', 'default' => 0],
        ['name' => 'mobile', 'type' => 'VARCHAR', 'length' => 20, 'default' => '', 'index' => 'mobile'],
        ['name' => 'school', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'qq', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'weibo', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'wechat', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'facebook', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'twitter', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'skype', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'line', 'type' => 'VARCHAR', 'length' => 200, 'default' => ''],
        ['name' => 'spare', 'type' => 'TEXT']
    ],
    'take' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'takename', 'type' => 'VARCHAR', 'length' => 50, 'default' => '', 'index' => 'takename'],
        ['name' => 'takevalue', 'type' => 'TEXT'],
        ['name' => 'taketype', 'type' => 'VARCHAR', 'length' => 30, 'default' => ''],
        ['name' => 'backstage', 'type' => 'VARCHAR', 'length' => 30, 'default' => ''],
    ],
    'categories' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'name', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'slug', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'slug'],
        ['name' => 'keyword', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'template', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'sort', 'type' => 'INT', 'default' => 0, 'index' => 'sort'],
        ['name' => 'parent', 'type' => 'UINT'],
        ['name' => 'description', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'tags' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'name', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'name'],
        ['name' => 'slug', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'slug'],
        ['name' => 'keyword', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'template', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'quantity', 'type' => 'INT', 'default' => 0, 'index' => 'quantity'],
        ['name' => 'description', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'postags' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'pid', 'type' => 'UINT', 'index' => 'pid'],
        ['name' => 'tid', 'type' => 'UINT', 'index' => 'tid'],
    ],
    'posts' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'uid', 'type' => 'UINT', 'index' => 'pid'],
        ['name' => 'cid', 'type' => 'UINT', 'index' => 'tid'],
        ['name' => 'title', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'slug', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'slug'],
        ['name' => 'keyword', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'template', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'source', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'thumbnail', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'comment', 'type' => 'INT', 'default' => 0, 'index' => 'comment'],
        ['name' => 'views', 'type' => 'INT', 'default' => 0, 'index' => 'views'],
        ['name' => 'likes', 'type' => 'INT', 'default' => 0],
        ['name' => 'dislikes', 'type' => 'INT', 'default' => 0],
        ['name' => 'createtime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'editime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'recommend', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'top', 'type' => 'TINYINT', 'default' => 0, 'index' => 'top'],
        ['name' => 'commentsoff', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'visibility', 'type' => 'SMALLINT', 'default' => 0],
        ['name' => 'password', 'type' => 'VARCHAR', 'length' => 64, 'default' => ''],
        ['name' => 'status', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'trash', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'trashuid', 'type' => 'INT', 'default' => 0],
        ['name' => 'summary', 'type' => 'TEXT'],
        ['name' => 'content', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'pages' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'title', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'slug', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'slug'],
        ['name' => 'keyword', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'template', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'thumbnail', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'views', 'type' => 'INT', 'default' => 0],
        ['name' => 'createtime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'editime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'visibility', 'type' => 'SMALLINT', 'default' => 0],
        ['name' => 'password', 'type' => 'VARCHAR', 'length' => 64, 'default' => ''],
        ['name' => 'status', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'parent', 'type' => 'UINT'],
        ['name' => 'sort', 'type' => 'UINT', 'index' => 'sort'],
        ['name' => 'summary', 'type' => 'TEXT'],
        ['name' => 'content', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'menu' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'name', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'slug', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'slug'],
        ['name' => 'sort', 'type' => 'UINT', 'index' => 'sort'],
        ['name' => 'parent', 'type' => 'UINT'],
        ['name' => 'icon', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'url', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'slide' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'name', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'gid', 'type' => 'UINT', 'index' => 'gid'],
        ['name' => 'sort', 'type' => 'UINT', 'index' => 'sort'],
        ['name' => 'image', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'url', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'description', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'slidegroup' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'name', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'slug', 'type' => 'VARCHAR', 'length' => 100, 'default' => '', 'index' => 'slug'],
        ['name' => 'width', 'type' => 'UINT'],
        ['name' => 'height', 'type' => 'UINT'],
        ['name' => 'description', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'links' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'name', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'sort', 'type' => 'UINT', 'index' => 'sort'],
        ['name' => 'image', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'url', 'type' => 'VARCHAR', 'length' => 300, 'default' => ''],
        ['name' => 'home', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'description', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ],
    'comments' => [
        ['name' => 'id', 'type' => 'AUTO'],
        ['name' => 'uid', 'type' => 'UINT', 'index' => 'uid'],
        ['name' => 'pid', 'type' => 'UINT', 'index' => 'pid'],
        ['name' => 'createtime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'editime', 'type' => 'DATETIME', 'default' => '1000-01-01 00:00:00'],
        ['name' => 'parent', 'type' => 'UINT'],
        ['name' => 'status', 'type' => 'TINYINT', 'default' => 0],
        ['name' => 'publicname', 'type' => 'VARCHAR', 'length' => 50, 'default' => ''],
        ['name' => 'email', 'type' => 'VARCHAR', 'length' => 100, 'default' => ''],
        ['name' => 'comment', 'type' => 'TEXT'],
        ['name' => 'spare', 'type' => 'TEXT'],
    ]
];